name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493  # v4

    - name: Set up Go
      uses: actions/setup-go@e75c3e80bcde46e322cd5845ae46582947c9becd  # v5
      with:
        cache: false

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@030ca6c9fbdb3112d99584f1992f5216eb38ad86  # v6
      with:
        version: latest
        args: --timeout=10m